### ISSUE TITLE
Email Template Checklist

### ISSUE THREAD

**Issue by lcaohoanq** [SWP391-613/Koi-Selling-BE#105]
- [ ] Notify user before Auction (x days)
- [x] Notify for all user in specific auction (1 winner, others lose)
- [x] Email notify that user are updating the Account Balance
- [ ] Email to user their order
